apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml

patchesJson6902:
  - target:
      name: demo
      namespace: default
      group: apps
      version: v1
      kind: Deployment
    path: patch.yaml
